channels:
    - conda-forge
dependencies:
    - python=3.8
    - geopandas=0.8.*
    - hs-process=0.0.4
    - scikit-learn=0.23.*
    - globus-sdk=1.9.*
    - tqdm=4.51.*
    - boto3=1.16.*
    - git=2.23.*
    - salib=1.3.*
    - pip=20.2.*
