#!/bin/bash -l
#PBS -l walltime=12:00:00,nodes=1:ppn=1,pmem=2580mb
#PBS -q small
#PBS -m abe
#PBS -M nigo0024@umn.edu
#PBS -N msi_1_train_41-48

cd $PBS_O_WORKDIR

((msi_run_id=1))
((start=40))
((n_jobs_tune=1))
CLIENT_ID="5d573462-2134-4900-970d-6e7a5e0f2b1e"
TRANSFER_TOKEN="AgBXVNMKXoOKa6XBlympD0pVKq3EkXxl03NkGB56YPqweBayGeFyClPv0n86GkyPK7PP0mgNM4GqNCk32vwoclEEN"
TRANSFER_REFRESH_TOKEN="AgxdYn0G06XqDYKmy21kpjmr7xkoP3kdBdrVzPOYag6z3vXp6eCeUNX4Pb4qwa4x9oW5O8DPo3KN684yoNKp05pKrGmyQ"
export msi_run_id start n_jobs_tune CLIENT_ID TRANSFER_TOKEN TRANSFER_REFRESH_TOKEN

conda activate msi_sip_37
module load parallel

parallel -u -j 1 < tune_plus_8_all.list
wait